project_name: elasticsearch-document-cleaner
env:
  - CGO_ENABLED=0
  - GOFLAGS=-mod=vendor
  - GO111MODULE=auto

before:
  hooks:
    - go mod vendor

builds:
  - id: binary
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w
    main: ./cmd/elasticsearch-document-cleaner/main.go
