---
project_name: elasticsearch-document-cleaner

env:
  - CGO_ENABLED=0
  - GO111MODULE=auto

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: binary
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w
    main: ./cmd/elasticsearch-document-cleaner/main.go

dockers:
  - image_templates:
      - "docker.io/bilalcaliskan/{{ .ProjectName }}:{{ .Version }}"
      - "docker.io/bilalcaliskan/{{ .ProjectName }}:latest"
    dockerfile: Dockerfile.goreleaser
    goos: linux
    goarch: amd64
    use: docker
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/bilalcaliskan/elasticsearch-document-cleaner
      - --label=org.opencontainers.image.source=https://github.com/bilalcaliskan/elasticsearch-document-cleaner
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache

archives:
  - replacements:
      amd64: x86_64

release:
  github:
    owner: bilalcaliskan
    name: elasticsearch-document-cleaner

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^build:'
      - 'README'
      - '^Merge branch'
      - '^Merge pull request'

brews:
  - name: elasticsearch-document-cleaner
    tap:
      owner: bilalcaliskan
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    folder: Formula
    goarm: 6
    homepage: https://github.com/bilalcaliskan/elasticsearch-document-cleaner
    license: apache-2.0
    description: elasticsearch-document-cleaner cleans documents in an Elasticsearch index with specific conditions
